// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Authentication Service API",
    "title": "Auth Service",
    "contact": {
      "name": "NEWS API Support"
    },
    "version": "1.0.0"
  },
  "basePath": "/news-api/v1",
  "paths": {
    "/add-news": {
      "$ref": "./paths/addNews.yml"
    },
    "/callback-facebook": {
      "$ref": "./paths/callbackFacebook.yml"
    },
    "/callback-facebook-login": {
      "$ref": "./paths/callbackFacebookLogin.yml"
    },
    "/callback-google": {
      "$ref": "./paths/callbackGoogle.yml"
    },
    "/callback-google-login": {
      "$ref": "./paths/callbackGoogleLogin.yml"
    },
    "/dashboard-details/{email}/{type}": {
      "$ref": "./paths/dashboardDetails.yml"
    },
    "/dashboard-setup": {
      "$ref": "./paths/dashboardSetup.yml"
    },
    "/lock-user": {
      "$ref": "./paths/lockUser.yml"
    },
    "/login": {
      "$ref": "./paths/login.yml"
    },
    "/news": {
      "$ref": "./paths/news.yml"
    },
    "/refresh-token": {
      "$ref": "./paths/refreshToken.yml"
    },
    "/register": {
      "$ref": "./paths/register.yml"
    },
    "/register-confirmation/{token}": {
      "$ref": "./paths/registerConfirmation.yml"
    },
    "/register-details": {
      "$ref": "./paths/registerDetails.yml"
    },
    "/reset-password": {
      "$ref": "./paths/resetPassword.yml"
    },
    "/reset-password-confirmation/{token}": {
      "$ref": "./paths/resetPasswordConf.yml"
    },
    "/reset-password-request/{email}": {
      "$ref": "./paths/resetPasswordReq.yml"
    },
    "/users": {
      "$ref": "./paths/users.yml"
    }
  },
  "definitions": {
    "generalResponse": {
      "$ref": "./definitions/generalResponse.yml"
    },
    "loginResponse": {
      "$ref": "./definitions/loginResponse.yml"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Authentication Service API",
    "title": "Auth Service",
    "contact": {
      "name": "NEWS API Support"
    },
    "version": "1.0.0"
  },
  "basePath": "/news-api/v1",
  "paths": {
    "/add-news": {
      "post": {
        "tags": [
          "news"
        ],
        "parameters": [
          {
            "name": "addNewsRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/news"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/callback-facebook": {
      "get": {
        "tags": [
          "register"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/callback-facebook-login": {
      "get": {
        "tags": [
          "login"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/callback-google": {
      "get": {
        "tags": [
          "register"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/callback-google-login": {
      "get": {
        "tags": [
          "login"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/dashboard-details/{email}/{type}": {
      "get": {
        "tags": [
          "page-management"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "email",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "type",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/dashboardDetailsResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/dashboard-setup": {
      "post": {
        "tags": [
          "page-management"
        ],
        "parameters": [
          {
            "name": "dashboardSetupRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/dashboardSetupRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/lock-user": {
      "post": {
        "tags": [
          "users-management"
        ],
        "parameters": [
          {
            "name": "lockUserRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/lockUserRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "login"
        ],
        "parameters": [
          {
            "name": "loginRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/loginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/news": {
      "get": {
        "tags": [
          "news"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/allNewsResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/refresh-token": {
      "get": {
        "tags": [
          "login"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/loginResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "tags": [
          "register"
        ],
        "parameters": [
          {
            "name": "registerRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/registerRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/register-confirmation/{token}": {
      "get": {
        "tags": [
          "register"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "token",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/register-details": {
      "post": {
        "tags": [
          "register"
        ],
        "parameters": [
          {
            "name": "registerRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/registerDetailsRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/reset-password": {
      "post": {
        "tags": [
          "login"
        ],
        "parameters": [
          {
            "name": "passwordRequest",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/passwordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/reset-password-confirmation/{token}": {
      "get": {
        "tags": [
          "login"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "token",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/userEmailResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/reset-password-request/{email}": {
      "get": {
        "tags": [
          "login"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "email",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "users-management"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/allUsersResponse"
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "401": {
            "description": "UNAUTHORIZED",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "403": {
            "description": "FORBIDDEN",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "404": {
            "description": "NOT FOUND",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "schema": {
              "$ref": "#/definitions/generalResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "allNewsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "description": {
                "description": "string"
              },
              "headline": {
                "headline": "string"
              },
              "imageUrl": {
                "imageUrl": "string"
              }
            }
          },
          "name": "news-list"
        },
        "error": {
          "properties": {
            "code": {
              "code": "int"
            },
            "message": {
              "message": "string"
            }
          },
          "error": "object"
        },
        "success": {
          "success": "boolean"
        }
      }
    },
    "allUsersResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "locked": {
                "locked": "boolean"
              },
              "mode": {
                "mode": "string"
              },
              "name": {
                "name": "string"
              },
              "ref": {
                "ref": "string"
              },
              "role": {
                "role": "string"
              }
            }
          },
          "name": "news-list"
        },
        "error": {
          "properties": {
            "code": {
              "code": "int"
            },
            "message": {
              "message": "string"
            }
          },
          "error": "object"
        },
        "success": {
          "success": "boolean"
        }
      }
    },
    "dashboardDetailsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "properties": {
            "bgColor": {
              "bgColor": "string"
            },
            "fontColor": {
              "fontColor": "string"
            },
            "logoURL": {
              "logoURL": "string"
            },
            "newsfeedBGColor": {
              "newsfeedBGColor": "string"
            },
            "newsfeedFontColor": {
              "newsfeedFontColor": "string"
            },
            "organization": {
              "organization": "string"
            },
            "userRef": {
              "userRef": "string"
            },
            "userType": {
              "userType": "string"
            }
          },
          "response": "object"
        },
        "error": {
          "properties": {
            "code": {
              "code": "int"
            },
            "message": {
              "message": "string"
            }
          },
          "error": "object"
        },
        "success": {
          "success": "boolean"
        }
      }
    },
    "dashboardSetupRequest": {
      "type": "object",
      "properties": {
        "bgColor": {
          "bgColor": "string"
        },
        "fontColor": {
          "fontColor": "string"
        },
        "logoURL": {
          "logoURL": "string"
        },
        "newseedFontColor": {
          "newseedFontColor": "string"
        },
        "newsfeedBGColor": {
          "newsfeedBGColor": "string"
        },
        "organization": {
          "organization": "string"
        },
        "userRef": {
          "userRef": "string"
        },
        "userType": {
          "userType": "string"
        }
      }
    },
    "generalResponse": {
      "type": "object",
      "properties": {
        "error": {
          "properties": {
            "code": {
              "code": "int"
            },
            "message": {
              "message": "string"
            }
          },
          "error": "object"
        },
        "message": {
          "message": "string"
        },
        "success": {
          "success": "boolean"
        }
      }
    },
    "lockUserRequest": {
      "type": "object",
      "properties": {
        "cred": {
          "cred": "string"
        },
        "lock": {
          "lock": "boolean"
        },
        "mode": {
          "mode": "string"
        }
      }
    },
    "loginRequest": {
      "type": "object",
      "properties": {
        "email": {
          "email": "string"
        },
        "password": {
          "password": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "loginResponse": {
      "type": "object",
      "properties": {
        "data": {
          "properties": {
            "accessToken": {
              "accessToken": "string"
            },
            "expiresIn": {
              "expiresIn": "string"
            },
            "role": {
              "role": "string"
            }
          },
          "response": "object"
        },
        "error": {
          "properties": {
            "code": {
              "code": "int"
            },
            "message": {
              "message": "string"
            }
          },
          "error": "object"
        },
        "success": {
          "success": "boolean"
        }
      }
    },
    "news": {
      "type": "object",
      "properties": {
        "description": {
          "description": "string"
        },
        "headline": {
          "headline": "string"
        },
        "imageUrl": {
          "imageUrl": "string"
        }
      }
    },
    "passwordRequest": {
      "type": "object",
      "properties": {
        "email": {
          "email": "string"
        },
        "password": {
          "password": "string"
        }
      }
    },
    "registerDetailsRequest": {
      "type": "object",
      "properties": {
        "designation": {
          "designation": "string"
        },
        "employeeCount": {
          "employeeCount": "int"
        },
        "name": {
          "name": "string"
        },
        "organization": {
          "organization": "string"
        }
      }
    },
    "registerRequest": {
      "type": "object",
      "properties": {
        "email": {
          "email": "string"
        },
        "password": {
          "password": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "userEmailResponse": {
      "type": "object",
      "properties": {
        "data": {
          "properties": {
            "email": {
              "email": "string"
            },
            "message": {
              "message": "string"
            }
          },
          "response": "object"
        },
        "error": {
          "properties": {
            "code": {
              "code": "int"
            },
            "message": {
              "message": "string"
            }
          },
          "error": "object"
        },
        "success": {
          "success": "boolean"
        }
      }
    }
  }
}`))
}
