swagger: '2.0'
info:
  title: Auth Service
  description: Authentication Service API
  contact:
    name: NEWS API Support
  version: 1.0.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /register:
    $ref: ./paths/register.yml
  /callback-google:
    $ref: ./paths/callbackGoogle.yml
  /callback-google-login:
    $ref: ./paths/callbackGoogleLogin.yml
  /callback-facebook:
    $ref: ./paths/callbackFacebook.yml
  /callback-facebook-login:
    $ref: ./paths/callbackFacebookLogin.yml
  /register-confirmation/{token}:
    $ref: ./paths/registerConfirmation.yml
  /register-details:
    $ref: ./paths/registerDetails.yml
  /login:
    $ref: ./paths/login.yml
  /refresh-token:
    $ref: ./paths/refreshToken.yml
  /reset-password-request/{email}:
    $ref: ./paths/resetPasswordReq.yml
  /reset-password:
    $ref: ./paths/resetPassword.yml
  /reset-password-confirmation/{token}:
    $ref: ./paths/resetPasswordConf.yml
  /news:
    $ref: ./paths/news.yml
  /add-news:
    $ref: ./paths/addNews.yml
  /users:
    $ref: ./paths/users.yml
  /lock-user:
    $ref: ./paths/lockUser.yml
  /dashboard-details/{email}/{type}:
    $ref: ./paths/dashboardDetails.yml
  /dashboard-setup:
    $ref: ./paths/dashboardSetup.yml
  /toplevel-domain:
    $ref: ./paths/toplevelDomain.yml
definitions:
  generalResponse:
    $ref: ./definitions/generalResponse.yml
  loginResponse:
    $ref: ./definitions/loginResponse.yml

basePath: /news-api/v1