// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCallbackFacebookLoginHandlerFunc turns a function with the right signature into a get callback facebook login handler
type GetCallbackFacebookLoginHandlerFunc func(GetCallbackFacebookLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCallbackFacebookLoginHandlerFunc) Handle(params GetCallbackFacebookLoginParams) middleware.Responder {
	return fn(params)
}

// GetCallbackFacebookLoginHandler interface for that can handle valid get callback facebook login params
type GetCallbackFacebookLoginHandler interface {
	Handle(GetCallbackFacebookLoginParams) middleware.Responder
}

// NewGetCallbackFacebookLogin creates a new http.Handler for the get callback facebook login operation
func NewGetCallbackFacebookLogin(ctx *middleware.Context, handler GetCallbackFacebookLoginHandler) *GetCallbackFacebookLogin {
	return &GetCallbackFacebookLogin{Context: ctx, Handler: handler}
}

/*GetCallbackFacebookLogin swagger:route GET /callback-facebook-login login getCallbackFacebookLogin

GetCallbackFacebookLogin get callback facebook login API

*/
type GetCallbackFacebookLogin struct {
	Context *middleware.Context
	Handler GetCallbackFacebookLoginHandler
}

func (o *GetCallbackFacebookLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCallbackFacebookLoginParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
