// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// GetResetPasswordConfirmationTokenOKCode is the HTTP code returned for type GetResetPasswordConfirmationTokenOK
const GetResetPasswordConfirmationTokenOKCode int = 200

/*GetResetPasswordConfirmationTokenOK OK

swagger:response getResetPasswordConfirmationTokenOK
*/
type GetResetPasswordConfirmationTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserEmailResponse `json:"body,omitempty"`
}

// NewGetResetPasswordConfirmationTokenOK creates GetResetPasswordConfirmationTokenOK with default headers values
func NewGetResetPasswordConfirmationTokenOK() *GetResetPasswordConfirmationTokenOK {

	return &GetResetPasswordConfirmationTokenOK{}
}

// WithPayload adds the payload to the get reset password confirmation token o k response
func (o *GetResetPasswordConfirmationTokenOK) WithPayload(payload *models.UserEmailResponse) *GetResetPasswordConfirmationTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password confirmation token o k response
func (o *GetResetPasswordConfirmationTokenOK) SetPayload(payload *models.UserEmailResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordConfirmationTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordConfirmationTokenBadRequestCode is the HTTP code returned for type GetResetPasswordConfirmationTokenBadRequest
const GetResetPasswordConfirmationTokenBadRequestCode int = 400

/*GetResetPasswordConfirmationTokenBadRequest BAD REQUEST

swagger:response getResetPasswordConfirmationTokenBadRequest
*/
type GetResetPasswordConfirmationTokenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordConfirmationTokenBadRequest creates GetResetPasswordConfirmationTokenBadRequest with default headers values
func NewGetResetPasswordConfirmationTokenBadRequest() *GetResetPasswordConfirmationTokenBadRequest {

	return &GetResetPasswordConfirmationTokenBadRequest{}
}

// WithPayload adds the payload to the get reset password confirmation token bad request response
func (o *GetResetPasswordConfirmationTokenBadRequest) WithPayload(payload *models.GeneralResponse) *GetResetPasswordConfirmationTokenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password confirmation token bad request response
func (o *GetResetPasswordConfirmationTokenBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordConfirmationTokenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordConfirmationTokenUnauthorizedCode is the HTTP code returned for type GetResetPasswordConfirmationTokenUnauthorized
const GetResetPasswordConfirmationTokenUnauthorizedCode int = 401

/*GetResetPasswordConfirmationTokenUnauthorized UNAUTHORIZED

swagger:response getResetPasswordConfirmationTokenUnauthorized
*/
type GetResetPasswordConfirmationTokenUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordConfirmationTokenUnauthorized creates GetResetPasswordConfirmationTokenUnauthorized with default headers values
func NewGetResetPasswordConfirmationTokenUnauthorized() *GetResetPasswordConfirmationTokenUnauthorized {

	return &GetResetPasswordConfirmationTokenUnauthorized{}
}

// WithPayload adds the payload to the get reset password confirmation token unauthorized response
func (o *GetResetPasswordConfirmationTokenUnauthorized) WithPayload(payload *models.GeneralResponse) *GetResetPasswordConfirmationTokenUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password confirmation token unauthorized response
func (o *GetResetPasswordConfirmationTokenUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordConfirmationTokenUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordConfirmationTokenForbiddenCode is the HTTP code returned for type GetResetPasswordConfirmationTokenForbidden
const GetResetPasswordConfirmationTokenForbiddenCode int = 403

/*GetResetPasswordConfirmationTokenForbidden FORBIDDEN

swagger:response getResetPasswordConfirmationTokenForbidden
*/
type GetResetPasswordConfirmationTokenForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordConfirmationTokenForbidden creates GetResetPasswordConfirmationTokenForbidden with default headers values
func NewGetResetPasswordConfirmationTokenForbidden() *GetResetPasswordConfirmationTokenForbidden {

	return &GetResetPasswordConfirmationTokenForbidden{}
}

// WithPayload adds the payload to the get reset password confirmation token forbidden response
func (o *GetResetPasswordConfirmationTokenForbidden) WithPayload(payload *models.GeneralResponse) *GetResetPasswordConfirmationTokenForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password confirmation token forbidden response
func (o *GetResetPasswordConfirmationTokenForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordConfirmationTokenForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordConfirmationTokenNotFoundCode is the HTTP code returned for type GetResetPasswordConfirmationTokenNotFound
const GetResetPasswordConfirmationTokenNotFoundCode int = 404

/*GetResetPasswordConfirmationTokenNotFound NOT FOUND

swagger:response getResetPasswordConfirmationTokenNotFound
*/
type GetResetPasswordConfirmationTokenNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordConfirmationTokenNotFound creates GetResetPasswordConfirmationTokenNotFound with default headers values
func NewGetResetPasswordConfirmationTokenNotFound() *GetResetPasswordConfirmationTokenNotFound {

	return &GetResetPasswordConfirmationTokenNotFound{}
}

// WithPayload adds the payload to the get reset password confirmation token not found response
func (o *GetResetPasswordConfirmationTokenNotFound) WithPayload(payload *models.GeneralResponse) *GetResetPasswordConfirmationTokenNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password confirmation token not found response
func (o *GetResetPasswordConfirmationTokenNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordConfirmationTokenNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordConfirmationTokenInternalServerErrorCode is the HTTP code returned for type GetResetPasswordConfirmationTokenInternalServerError
const GetResetPasswordConfirmationTokenInternalServerErrorCode int = 500

/*GetResetPasswordConfirmationTokenInternalServerError INTERNAL SERVER ERROR

swagger:response getResetPasswordConfirmationTokenInternalServerError
*/
type GetResetPasswordConfirmationTokenInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordConfirmationTokenInternalServerError creates GetResetPasswordConfirmationTokenInternalServerError with default headers values
func NewGetResetPasswordConfirmationTokenInternalServerError() *GetResetPasswordConfirmationTokenInternalServerError {

	return &GetResetPasswordConfirmationTokenInternalServerError{}
}

// WithPayload adds the payload to the get reset password confirmation token internal server error response
func (o *GetResetPasswordConfirmationTokenInternalServerError) WithPayload(payload *models.GeneralResponse) *GetResetPasswordConfirmationTokenInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password confirmation token internal server error response
func (o *GetResetPasswordConfirmationTokenInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordConfirmationTokenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
