// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// GetResetPasswordRequestEmailOKCode is the HTTP code returned for type GetResetPasswordRequestEmailOK
const GetResetPasswordRequestEmailOKCode int = 200

/*GetResetPasswordRequestEmailOK OK

swagger:response getResetPasswordRequestEmailOK
*/
type GetResetPasswordRequestEmailOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordRequestEmailOK creates GetResetPasswordRequestEmailOK with default headers values
func NewGetResetPasswordRequestEmailOK() *GetResetPasswordRequestEmailOK {

	return &GetResetPasswordRequestEmailOK{}
}

// WithPayload adds the payload to the get reset password request email o k response
func (o *GetResetPasswordRequestEmailOK) WithPayload(payload *models.GeneralResponse) *GetResetPasswordRequestEmailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password request email o k response
func (o *GetResetPasswordRequestEmailOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordRequestEmailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordRequestEmailBadRequestCode is the HTTP code returned for type GetResetPasswordRequestEmailBadRequest
const GetResetPasswordRequestEmailBadRequestCode int = 400

/*GetResetPasswordRequestEmailBadRequest BAD REQUEST

swagger:response getResetPasswordRequestEmailBadRequest
*/
type GetResetPasswordRequestEmailBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordRequestEmailBadRequest creates GetResetPasswordRequestEmailBadRequest with default headers values
func NewGetResetPasswordRequestEmailBadRequest() *GetResetPasswordRequestEmailBadRequest {

	return &GetResetPasswordRequestEmailBadRequest{}
}

// WithPayload adds the payload to the get reset password request email bad request response
func (o *GetResetPasswordRequestEmailBadRequest) WithPayload(payload *models.GeneralResponse) *GetResetPasswordRequestEmailBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password request email bad request response
func (o *GetResetPasswordRequestEmailBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordRequestEmailBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordRequestEmailUnauthorizedCode is the HTTP code returned for type GetResetPasswordRequestEmailUnauthorized
const GetResetPasswordRequestEmailUnauthorizedCode int = 401

/*GetResetPasswordRequestEmailUnauthorized UNAUTHORIZED

swagger:response getResetPasswordRequestEmailUnauthorized
*/
type GetResetPasswordRequestEmailUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordRequestEmailUnauthorized creates GetResetPasswordRequestEmailUnauthorized with default headers values
func NewGetResetPasswordRequestEmailUnauthorized() *GetResetPasswordRequestEmailUnauthorized {

	return &GetResetPasswordRequestEmailUnauthorized{}
}

// WithPayload adds the payload to the get reset password request email unauthorized response
func (o *GetResetPasswordRequestEmailUnauthorized) WithPayload(payload *models.GeneralResponse) *GetResetPasswordRequestEmailUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password request email unauthorized response
func (o *GetResetPasswordRequestEmailUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordRequestEmailUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordRequestEmailForbiddenCode is the HTTP code returned for type GetResetPasswordRequestEmailForbidden
const GetResetPasswordRequestEmailForbiddenCode int = 403

/*GetResetPasswordRequestEmailForbidden FORBIDDEN

swagger:response getResetPasswordRequestEmailForbidden
*/
type GetResetPasswordRequestEmailForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordRequestEmailForbidden creates GetResetPasswordRequestEmailForbidden with default headers values
func NewGetResetPasswordRequestEmailForbidden() *GetResetPasswordRequestEmailForbidden {

	return &GetResetPasswordRequestEmailForbidden{}
}

// WithPayload adds the payload to the get reset password request email forbidden response
func (o *GetResetPasswordRequestEmailForbidden) WithPayload(payload *models.GeneralResponse) *GetResetPasswordRequestEmailForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password request email forbidden response
func (o *GetResetPasswordRequestEmailForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordRequestEmailForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordRequestEmailNotFoundCode is the HTTP code returned for type GetResetPasswordRequestEmailNotFound
const GetResetPasswordRequestEmailNotFoundCode int = 404

/*GetResetPasswordRequestEmailNotFound NOT FOUND

swagger:response getResetPasswordRequestEmailNotFound
*/
type GetResetPasswordRequestEmailNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordRequestEmailNotFound creates GetResetPasswordRequestEmailNotFound with default headers values
func NewGetResetPasswordRequestEmailNotFound() *GetResetPasswordRequestEmailNotFound {

	return &GetResetPasswordRequestEmailNotFound{}
}

// WithPayload adds the payload to the get reset password request email not found response
func (o *GetResetPasswordRequestEmailNotFound) WithPayload(payload *models.GeneralResponse) *GetResetPasswordRequestEmailNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password request email not found response
func (o *GetResetPasswordRequestEmailNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordRequestEmailNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResetPasswordRequestEmailInternalServerErrorCode is the HTTP code returned for type GetResetPasswordRequestEmailInternalServerError
const GetResetPasswordRequestEmailInternalServerErrorCode int = 500

/*GetResetPasswordRequestEmailInternalServerError INTERNAL SERVER ERROR

swagger:response getResetPasswordRequestEmailInternalServerError
*/
type GetResetPasswordRequestEmailInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetResetPasswordRequestEmailInternalServerError creates GetResetPasswordRequestEmailInternalServerError with default headers values
func NewGetResetPasswordRequestEmailInternalServerError() *GetResetPasswordRequestEmailInternalServerError {

	return &GetResetPasswordRequestEmailInternalServerError{}
}

// WithPayload adds the payload to the get reset password request email internal server error response
func (o *GetResetPasswordRequestEmailInternalServerError) WithPayload(payload *models.GeneralResponse) *GetResetPasswordRequestEmailInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get reset password request email internal server error response
func (o *GetResetPasswordRequestEmailInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResetPasswordRequestEmailInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
