// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRefreshTokenHandlerFunc turns a function with the right signature into a get refresh token handler
type GetRefreshTokenHandlerFunc func(GetRefreshTokenParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRefreshTokenHandlerFunc) Handle(params GetRefreshTokenParams) middleware.Responder {
	return fn(params)
}

// GetRefreshTokenHandler interface for that can handle valid get refresh token params
type GetRefreshTokenHandler interface {
	Handle(GetRefreshTokenParams) middleware.Responder
}

// NewGetRefreshToken creates a new http.Handler for the get refresh token operation
func NewGetRefreshToken(ctx *middleware.Context, handler GetRefreshTokenHandler) *GetRefreshToken {
	return &GetRefreshToken{Context: ctx, Handler: handler}
}

/*GetRefreshToken swagger:route GET /refresh-token login getRefreshToken

GetRefreshToken get refresh token API

*/
type GetRefreshToken struct {
	Context *middleware.Context
	Handler GetRefreshTokenHandler
}

func (o *GetRefreshToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRefreshTokenParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
