// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// GetCallbackGoogleLoginOKCode is the HTTP code returned for type GetCallbackGoogleLoginOK
const GetCallbackGoogleLoginOKCode int = 200

/*GetCallbackGoogleLoginOK OK

swagger:response getCallbackGoogleLoginOK
*/
type GetCallbackGoogleLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleLoginOK creates GetCallbackGoogleLoginOK with default headers values
func NewGetCallbackGoogleLoginOK() *GetCallbackGoogleLoginOK {

	return &GetCallbackGoogleLoginOK{}
}

// WithPayload adds the payload to the get callback google login o k response
func (o *GetCallbackGoogleLoginOK) WithPayload(payload *models.LoginResponse) *GetCallbackGoogleLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google login o k response
func (o *GetCallbackGoogleLoginOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleLoginBadRequestCode is the HTTP code returned for type GetCallbackGoogleLoginBadRequest
const GetCallbackGoogleLoginBadRequestCode int = 400

/*GetCallbackGoogleLoginBadRequest BAD REQUEST

swagger:response getCallbackGoogleLoginBadRequest
*/
type GetCallbackGoogleLoginBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleLoginBadRequest creates GetCallbackGoogleLoginBadRequest with default headers values
func NewGetCallbackGoogleLoginBadRequest() *GetCallbackGoogleLoginBadRequest {

	return &GetCallbackGoogleLoginBadRequest{}
}

// WithPayload adds the payload to the get callback google login bad request response
func (o *GetCallbackGoogleLoginBadRequest) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleLoginBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google login bad request response
func (o *GetCallbackGoogleLoginBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleLoginUnauthorizedCode is the HTTP code returned for type GetCallbackGoogleLoginUnauthorized
const GetCallbackGoogleLoginUnauthorizedCode int = 401

/*GetCallbackGoogleLoginUnauthorized UNAUTHORIZED

swagger:response getCallbackGoogleLoginUnauthorized
*/
type GetCallbackGoogleLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleLoginUnauthorized creates GetCallbackGoogleLoginUnauthorized with default headers values
func NewGetCallbackGoogleLoginUnauthorized() *GetCallbackGoogleLoginUnauthorized {

	return &GetCallbackGoogleLoginUnauthorized{}
}

// WithPayload adds the payload to the get callback google login unauthorized response
func (o *GetCallbackGoogleLoginUnauthorized) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google login unauthorized response
func (o *GetCallbackGoogleLoginUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleLoginForbiddenCode is the HTTP code returned for type GetCallbackGoogleLoginForbidden
const GetCallbackGoogleLoginForbiddenCode int = 403

/*GetCallbackGoogleLoginForbidden FORBIDDEN

swagger:response getCallbackGoogleLoginForbidden
*/
type GetCallbackGoogleLoginForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleLoginForbidden creates GetCallbackGoogleLoginForbidden with default headers values
func NewGetCallbackGoogleLoginForbidden() *GetCallbackGoogleLoginForbidden {

	return &GetCallbackGoogleLoginForbidden{}
}

// WithPayload adds the payload to the get callback google login forbidden response
func (o *GetCallbackGoogleLoginForbidden) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleLoginForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google login forbidden response
func (o *GetCallbackGoogleLoginForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleLoginForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleLoginNotFoundCode is the HTTP code returned for type GetCallbackGoogleLoginNotFound
const GetCallbackGoogleLoginNotFoundCode int = 404

/*GetCallbackGoogleLoginNotFound NOT FOUND

swagger:response getCallbackGoogleLoginNotFound
*/
type GetCallbackGoogleLoginNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleLoginNotFound creates GetCallbackGoogleLoginNotFound with default headers values
func NewGetCallbackGoogleLoginNotFound() *GetCallbackGoogleLoginNotFound {

	return &GetCallbackGoogleLoginNotFound{}
}

// WithPayload adds the payload to the get callback google login not found response
func (o *GetCallbackGoogleLoginNotFound) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleLoginNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google login not found response
func (o *GetCallbackGoogleLoginNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleLoginNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleLoginInternalServerErrorCode is the HTTP code returned for type GetCallbackGoogleLoginInternalServerError
const GetCallbackGoogleLoginInternalServerErrorCode int = 500

/*GetCallbackGoogleLoginInternalServerError INTERNAL SERVER ERROR

swagger:response getCallbackGoogleLoginInternalServerError
*/
type GetCallbackGoogleLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleLoginInternalServerError creates GetCallbackGoogleLoginInternalServerError with default headers values
func NewGetCallbackGoogleLoginInternalServerError() *GetCallbackGoogleLoginInternalServerError {

	return &GetCallbackGoogleLoginInternalServerError{}
}

// WithPayload adds the payload to the get callback google login internal server error response
func (o *GetCallbackGoogleLoginInternalServerError) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google login internal server error response
func (o *GetCallbackGoogleLoginInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
