// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCallbackGoogleLoginHandlerFunc turns a function with the right signature into a get callback google login handler
type GetCallbackGoogleLoginHandlerFunc func(GetCallbackGoogleLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCallbackGoogleLoginHandlerFunc) Handle(params GetCallbackGoogleLoginParams) middleware.Responder {
	return fn(params)
}

// GetCallbackGoogleLoginHandler interface for that can handle valid get callback google login params
type GetCallbackGoogleLoginHandler interface {
	Handle(GetCallbackGoogleLoginParams) middleware.Responder
}

// NewGetCallbackGoogleLogin creates a new http.Handler for the get callback google login operation
func NewGetCallbackGoogleLogin(ctx *middleware.Context, handler GetCallbackGoogleLoginHandler) *GetCallbackGoogleLogin {
	return &GetCallbackGoogleLogin{Context: ctx, Handler: handler}
}

/*GetCallbackGoogleLogin swagger:route GET /callback-google-login login getCallbackGoogleLogin

GetCallbackGoogleLogin get callback google login API

*/
type GetCallbackGoogleLogin struct {
	Context *middleware.Context
	Handler GetCallbackGoogleLoginHandler
}

func (o *GetCallbackGoogleLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCallbackGoogleLoginParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
