// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostResetPasswordHandlerFunc turns a function with the right signature into a post reset password handler
type PostResetPasswordHandlerFunc func(PostResetPasswordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostResetPasswordHandlerFunc) Handle(params PostResetPasswordParams) middleware.Responder {
	return fn(params)
}

// PostResetPasswordHandler interface for that can handle valid post reset password params
type PostResetPasswordHandler interface {
	Handle(PostResetPasswordParams) middleware.Responder
}

// NewPostResetPassword creates a new http.Handler for the post reset password operation
func NewPostResetPassword(ctx *middleware.Context, handler PostResetPasswordHandler) *PostResetPassword {
	return &PostResetPassword{Context: ctx, Handler: handler}
}

/*PostResetPassword swagger:route POST /reset-password login postResetPassword

PostResetPassword post reset password API

*/
type PostResetPassword struct {
	Context *middleware.Context
	Handler PostResetPasswordHandler
}

func (o *PostResetPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostResetPasswordParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
