// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostLockUserHandlerFunc turns a function with the right signature into a post lock user handler
type PostLockUserHandlerFunc func(PostLockUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLockUserHandlerFunc) Handle(params PostLockUserParams) middleware.Responder {
	return fn(params)
}

// PostLockUserHandler interface for that can handle valid post lock user params
type PostLockUserHandler interface {
	Handle(PostLockUserParams) middleware.Responder
}

// NewPostLockUser creates a new http.Handler for the post lock user operation
func NewPostLockUser(ctx *middleware.Context, handler PostLockUserHandler) *PostLockUser {
	return &PostLockUser{Context: ctx, Handler: handler}
}

/*PostLockUser swagger:route POST /lock-user login postLockUser

PostLockUser post lock user API

*/
type PostLockUser struct {
	Context *middleware.Context
	Handler PostLockUserHandler
}

func (o *PostLockUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostLockUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
