// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// PostResetPasswordOKCode is the HTTP code returned for type PostResetPasswordOK
const PostResetPasswordOKCode int = 200

/*PostResetPasswordOK OK

swagger:response postResetPasswordOK
*/
type PostResetPasswordOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewPostResetPasswordOK creates PostResetPasswordOK with default headers values
func NewPostResetPasswordOK() *PostResetPasswordOK {

	return &PostResetPasswordOK{}
}

// WithPayload adds the payload to the post reset password o k response
func (o *PostResetPasswordOK) WithPayload(payload *models.GeneralResponse) *PostResetPasswordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reset password o k response
func (o *PostResetPasswordOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResetPasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResetPasswordBadRequestCode is the HTTP code returned for type PostResetPasswordBadRequest
const PostResetPasswordBadRequestCode int = 400

/*PostResetPasswordBadRequest BAD REQUEST

swagger:response postResetPasswordBadRequest
*/
type PostResetPasswordBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewPostResetPasswordBadRequest creates PostResetPasswordBadRequest with default headers values
func NewPostResetPasswordBadRequest() *PostResetPasswordBadRequest {

	return &PostResetPasswordBadRequest{}
}

// WithPayload adds the payload to the post reset password bad request response
func (o *PostResetPasswordBadRequest) WithPayload(payload *models.GeneralResponse) *PostResetPasswordBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reset password bad request response
func (o *PostResetPasswordBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResetPasswordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResetPasswordUnauthorizedCode is the HTTP code returned for type PostResetPasswordUnauthorized
const PostResetPasswordUnauthorizedCode int = 401

/*PostResetPasswordUnauthorized UNAUTHORIZED

swagger:response postResetPasswordUnauthorized
*/
type PostResetPasswordUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewPostResetPasswordUnauthorized creates PostResetPasswordUnauthorized with default headers values
func NewPostResetPasswordUnauthorized() *PostResetPasswordUnauthorized {

	return &PostResetPasswordUnauthorized{}
}

// WithPayload adds the payload to the post reset password unauthorized response
func (o *PostResetPasswordUnauthorized) WithPayload(payload *models.GeneralResponse) *PostResetPasswordUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reset password unauthorized response
func (o *PostResetPasswordUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResetPasswordUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResetPasswordForbiddenCode is the HTTP code returned for type PostResetPasswordForbidden
const PostResetPasswordForbiddenCode int = 403

/*PostResetPasswordForbidden FORBIDDEN

swagger:response postResetPasswordForbidden
*/
type PostResetPasswordForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewPostResetPasswordForbidden creates PostResetPasswordForbidden with default headers values
func NewPostResetPasswordForbidden() *PostResetPasswordForbidden {

	return &PostResetPasswordForbidden{}
}

// WithPayload adds the payload to the post reset password forbidden response
func (o *PostResetPasswordForbidden) WithPayload(payload *models.GeneralResponse) *PostResetPasswordForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reset password forbidden response
func (o *PostResetPasswordForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResetPasswordForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResetPasswordNotFoundCode is the HTTP code returned for type PostResetPasswordNotFound
const PostResetPasswordNotFoundCode int = 404

/*PostResetPasswordNotFound NOT FOUND

swagger:response postResetPasswordNotFound
*/
type PostResetPasswordNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewPostResetPasswordNotFound creates PostResetPasswordNotFound with default headers values
func NewPostResetPasswordNotFound() *PostResetPasswordNotFound {

	return &PostResetPasswordNotFound{}
}

// WithPayload adds the payload to the post reset password not found response
func (o *PostResetPasswordNotFound) WithPayload(payload *models.GeneralResponse) *PostResetPasswordNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reset password not found response
func (o *PostResetPasswordNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResetPasswordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResetPasswordInternalServerErrorCode is the HTTP code returned for type PostResetPasswordInternalServerError
const PostResetPasswordInternalServerErrorCode int = 500

/*PostResetPasswordInternalServerError INTERNAL SERVER ERROR

swagger:response postResetPasswordInternalServerError
*/
type PostResetPasswordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewPostResetPasswordInternalServerError creates PostResetPasswordInternalServerError with default headers values
func NewPostResetPasswordInternalServerError() *PostResetPasswordInternalServerError {

	return &PostResetPasswordInternalServerError{}
}

// WithPayload adds the payload to the post reset password internal server error response
func (o *PostResetPasswordInternalServerError) WithPayload(payload *models.GeneralResponse) *PostResetPasswordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post reset password internal server error response
func (o *PostResetPasswordInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResetPasswordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
