// Code generated by go-swagger; DO NOT EDIT.

package page_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetDashboardDetailsEmailTypeURL generates an URL for the get dashboard details email type operation
type GetDashboardDetailsEmailTypeURL struct {
	Email string
	Type  string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDashboardDetailsEmailTypeURL) WithBasePath(bp string) *GetDashboardDetailsEmailTypeURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetDashboardDetailsEmailTypeURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetDashboardDetailsEmailTypeURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/dashboard-details/{email}/{type}"

	email := o.Email
	if email != "" {
		_path = strings.Replace(_path, "{email}", email, -1)
	} else {
		return nil, errors.New("email is required on GetDashboardDetailsEmailTypeURL")
	}

	typeVar := o.Type
	if typeVar != "" {
		_path = strings.Replace(_path, "{type}", typeVar, -1)
	} else {
		return nil, errors.New("type is required on GetDashboardDetailsEmailTypeURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/news-api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetDashboardDetailsEmailTypeURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetDashboardDetailsEmailTypeURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetDashboardDetailsEmailTypeURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetDashboardDetailsEmailTypeURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetDashboardDetailsEmailTypeURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetDashboardDetailsEmailTypeURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
