// Code generated by go-swagger; DO NOT EDIT.

package page_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// GetDashboardDetailsEmailTypeOKCode is the HTTP code returned for type GetDashboardDetailsEmailTypeOK
const GetDashboardDetailsEmailTypeOKCode int = 200

/*GetDashboardDetailsEmailTypeOK OK

swagger:response getDashboardDetailsEmailTypeOK
*/
type GetDashboardDetailsEmailTypeOK struct {

	/*
	  In: Body
	*/
	Payload *models.DashboardDetailsResponse `json:"body,omitempty"`
}

// NewGetDashboardDetailsEmailTypeOK creates GetDashboardDetailsEmailTypeOK with default headers values
func NewGetDashboardDetailsEmailTypeOK() *GetDashboardDetailsEmailTypeOK {

	return &GetDashboardDetailsEmailTypeOK{}
}

// WithPayload adds the payload to the get dashboard details email type o k response
func (o *GetDashboardDetailsEmailTypeOK) WithPayload(payload *models.DashboardDetailsResponse) *GetDashboardDetailsEmailTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard details email type o k response
func (o *GetDashboardDetailsEmailTypeOK) SetPayload(payload *models.DashboardDetailsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardDetailsEmailTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDashboardDetailsEmailTypeBadRequestCode is the HTTP code returned for type GetDashboardDetailsEmailTypeBadRequest
const GetDashboardDetailsEmailTypeBadRequestCode int = 400

/*GetDashboardDetailsEmailTypeBadRequest BAD REQUEST

swagger:response getDashboardDetailsEmailTypeBadRequest
*/
type GetDashboardDetailsEmailTypeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetDashboardDetailsEmailTypeBadRequest creates GetDashboardDetailsEmailTypeBadRequest with default headers values
func NewGetDashboardDetailsEmailTypeBadRequest() *GetDashboardDetailsEmailTypeBadRequest {

	return &GetDashboardDetailsEmailTypeBadRequest{}
}

// WithPayload adds the payload to the get dashboard details email type bad request response
func (o *GetDashboardDetailsEmailTypeBadRequest) WithPayload(payload *models.GeneralResponse) *GetDashboardDetailsEmailTypeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard details email type bad request response
func (o *GetDashboardDetailsEmailTypeBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardDetailsEmailTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDashboardDetailsEmailTypeUnauthorizedCode is the HTTP code returned for type GetDashboardDetailsEmailTypeUnauthorized
const GetDashboardDetailsEmailTypeUnauthorizedCode int = 401

/*GetDashboardDetailsEmailTypeUnauthorized UNAUTHORIZED

swagger:response getDashboardDetailsEmailTypeUnauthorized
*/
type GetDashboardDetailsEmailTypeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetDashboardDetailsEmailTypeUnauthorized creates GetDashboardDetailsEmailTypeUnauthorized with default headers values
func NewGetDashboardDetailsEmailTypeUnauthorized() *GetDashboardDetailsEmailTypeUnauthorized {

	return &GetDashboardDetailsEmailTypeUnauthorized{}
}

// WithPayload adds the payload to the get dashboard details email type unauthorized response
func (o *GetDashboardDetailsEmailTypeUnauthorized) WithPayload(payload *models.GeneralResponse) *GetDashboardDetailsEmailTypeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard details email type unauthorized response
func (o *GetDashboardDetailsEmailTypeUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardDetailsEmailTypeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDashboardDetailsEmailTypeForbiddenCode is the HTTP code returned for type GetDashboardDetailsEmailTypeForbidden
const GetDashboardDetailsEmailTypeForbiddenCode int = 403

/*GetDashboardDetailsEmailTypeForbidden FORBIDDEN

swagger:response getDashboardDetailsEmailTypeForbidden
*/
type GetDashboardDetailsEmailTypeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetDashboardDetailsEmailTypeForbidden creates GetDashboardDetailsEmailTypeForbidden with default headers values
func NewGetDashboardDetailsEmailTypeForbidden() *GetDashboardDetailsEmailTypeForbidden {

	return &GetDashboardDetailsEmailTypeForbidden{}
}

// WithPayload adds the payload to the get dashboard details email type forbidden response
func (o *GetDashboardDetailsEmailTypeForbidden) WithPayload(payload *models.GeneralResponse) *GetDashboardDetailsEmailTypeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard details email type forbidden response
func (o *GetDashboardDetailsEmailTypeForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardDetailsEmailTypeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDashboardDetailsEmailTypeNotFoundCode is the HTTP code returned for type GetDashboardDetailsEmailTypeNotFound
const GetDashboardDetailsEmailTypeNotFoundCode int = 404

/*GetDashboardDetailsEmailTypeNotFound NOT FOUND

swagger:response getDashboardDetailsEmailTypeNotFound
*/
type GetDashboardDetailsEmailTypeNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetDashboardDetailsEmailTypeNotFound creates GetDashboardDetailsEmailTypeNotFound with default headers values
func NewGetDashboardDetailsEmailTypeNotFound() *GetDashboardDetailsEmailTypeNotFound {

	return &GetDashboardDetailsEmailTypeNotFound{}
}

// WithPayload adds the payload to the get dashboard details email type not found response
func (o *GetDashboardDetailsEmailTypeNotFound) WithPayload(payload *models.GeneralResponse) *GetDashboardDetailsEmailTypeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard details email type not found response
func (o *GetDashboardDetailsEmailTypeNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardDetailsEmailTypeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDashboardDetailsEmailTypeInternalServerErrorCode is the HTTP code returned for type GetDashboardDetailsEmailTypeInternalServerError
const GetDashboardDetailsEmailTypeInternalServerErrorCode int = 500

/*GetDashboardDetailsEmailTypeInternalServerError INTERNAL SERVER ERROR

swagger:response getDashboardDetailsEmailTypeInternalServerError
*/
type GetDashboardDetailsEmailTypeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetDashboardDetailsEmailTypeInternalServerError creates GetDashboardDetailsEmailTypeInternalServerError with default headers values
func NewGetDashboardDetailsEmailTypeInternalServerError() *GetDashboardDetailsEmailTypeInternalServerError {

	return &GetDashboardDetailsEmailTypeInternalServerError{}
}

// WithPayload adds the payload to the get dashboard details email type internal server error response
func (o *GetDashboardDetailsEmailTypeInternalServerError) WithPayload(payload *models.GeneralResponse) *GetDashboardDetailsEmailTypeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard details email type internal server error response
func (o *GetDashboardDetailsEmailTypeInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardDetailsEmailTypeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
