// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DashboardSetupRequest dashboard setup request
// swagger:model dashboardSetupRequest
type DashboardSetupRequest struct {

	// bg color
	BgColor interface{} `json:"bgColor,omitempty"`

	// font color
	FontColor interface{} `json:"fontColor,omitempty"`

	// logo URL
	LogoURL interface{} `json:"logoURL,omitempty"`

	// newseed font color
	NewseedFontColor interface{} `json:"newseedFontColor,omitempty"`

	// newsfeed b g color
	NewsfeedBGColor interface{} `json:"newsfeedBGColor,omitempty"`

	// organization
	Organization interface{} `json:"organization,omitempty"`

	// user ref
	UserRef interface{} `json:"userRef,omitempty"`

	// user type
	UserType interface{} `json:"userType,omitempty"`
}

// Validate validates this dashboard setup request
func (m *DashboardSetupRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DashboardSetupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DashboardSetupRequest) UnmarshalBinary(b []byte) error {
	var res DashboardSetupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
