// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DashboardDetailsResponse dashboard details response
// swagger:model dashboardDetailsResponse
type DashboardDetailsResponse struct {

	// data
	Data *DashboardDetailsResponseData `json:"data,omitempty"`

	// error
	Error *DashboardDetailsResponseError `json:"error,omitempty"`

	// success
	Success interface{} `json:"success,omitempty"`
}

// Validate validates this dashboard details response
func (m *DashboardDetailsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DashboardDetailsResponse) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if m.Data != nil {
		if err := m.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("data")
			}
			return err
		}
	}

	return nil
}

func (m *DashboardDetailsResponse) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DashboardDetailsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DashboardDetailsResponse) UnmarshalBinary(b []byte) error {
	var res DashboardDetailsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DashboardDetailsResponseData dashboard details response data
// swagger:model DashboardDetailsResponseData
type DashboardDetailsResponseData struct {

	// bg color
	BgColor interface{} `json:"bgColor,omitempty"`

	// font color
	FontColor interface{} `json:"fontColor,omitempty"`

	// logo URL
	LogoURL interface{} `json:"logoURL,omitempty"`

	// newsfeed b g color
	NewsfeedBGColor interface{} `json:"newsfeedBGColor,omitempty"`

	// newsfeed font color
	NewsfeedFontColor interface{} `json:"newsfeedFontColor,omitempty"`

	// organization
	Organization interface{} `json:"organization,omitempty"`

	// user ref
	UserRef interface{} `json:"userRef,omitempty"`

	// user type
	UserType interface{} `json:"userType,omitempty"`
}

// Validate validates this dashboard details response data
func (m *DashboardDetailsResponseData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DashboardDetailsResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DashboardDetailsResponseData) UnmarshalBinary(b []byte) error {
	var res DashboardDetailsResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DashboardDetailsResponseError dashboard details response error
// swagger:model DashboardDetailsResponseError
type DashboardDetailsResponseError struct {

	// code
	Code interface{} `json:"code,omitempty"`

	// message
	Message interface{} `json:"message,omitempty"`
}

// Validate validates this dashboard details response error
func (m *DashboardDetailsResponseError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DashboardDetailsResponseError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DashboardDetailsResponseError) UnmarshalBinary(b []byte) error {
	var res DashboardDetailsResponseError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
