// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LockUserRequest lock user request
// swagger:model lockUserRequest
type LockUserRequest struct {

	// cred
	Cred interface{} `json:"cred,omitempty"`

	// lock
	Lock interface{} `json:"lock,omitempty"`

	// mode
	Mode interface{} `json:"mode,omitempty"`
}

// Validate validates this lock user request
func (m *LockUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LockUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LockUserRequest) UnmarshalBinary(b []byte) error {
	var res LockUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
