// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// News news
// swagger:model news
type News struct {

	// string
	Description interface{} `json:"description,omitempty"`

	// headline
	Headline interface{} `json:"headline,omitempty"`

	// image Url
	ImageURL interface{} `json:"imageUrl,omitempty"`
}

// Validate validates this news
func (m *News) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *News) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *News) UnmarshalBinary(b []byte) error {
	var res News
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
