// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ToplevelDomain toplevel domain
// swagger:model toplevelDomain
type ToplevelDomain struct {

	// string
	Description interface{} `json:"description,omitempty"`

	// name
	Name interface{} `json:"name,omitempty"`

	// owner
	Owner interface{} `json:"owner,omitempty"`
}

// Validate validates this toplevel domain
func (m *ToplevelDomain) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ToplevelDomain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ToplevelDomain) UnmarshalBinary(b []byte) error {
	var res ToplevelDomain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
