// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCallbackFacebookHandlerFunc turns a function with the right signature into a get callback facebook handler
type GetCallbackFacebookHandlerFunc func(GetCallbackFacebookParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCallbackFacebookHandlerFunc) Handle(params GetCallbackFacebookParams) middleware.Responder {
	return fn(params)
}

// GetCallbackFacebookHandler interface for that can handle valid get callback facebook params
type GetCallbackFacebookHandler interface {
	Handle(GetCallbackFacebookParams) middleware.Responder
}

// NewGetCallbackFacebook creates a new http.Handler for the get callback facebook operation
func NewGetCallbackFacebook(ctx *middleware.Context, handler GetCallbackFacebookHandler) *GetCallbackFacebook {
	return &GetCallbackFacebook{Context: ctx, Handler: handler}
}

/*GetCallbackFacebook swagger:route GET /callback-facebook register getCallbackFacebook

GetCallbackFacebook get callback facebook API

*/
type GetCallbackFacebook struct {
	Context *middleware.Context
	Handler GetCallbackFacebookHandler
}

func (o *GetCallbackFacebook) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCallbackFacebookParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
