// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRegisterConfirmationTokenHandlerFunc turns a function with the right signature into a get register confirmation token handler
type GetRegisterConfirmationTokenHandlerFunc func(GetRegisterConfirmationTokenParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRegisterConfirmationTokenHandlerFunc) Handle(params GetRegisterConfirmationTokenParams) middleware.Responder {
	return fn(params)
}

// GetRegisterConfirmationTokenHandler interface for that can handle valid get register confirmation token params
type GetRegisterConfirmationTokenHandler interface {
	Handle(GetRegisterConfirmationTokenParams) middleware.Responder
}

// NewGetRegisterConfirmationToken creates a new http.Handler for the get register confirmation token operation
func NewGetRegisterConfirmationToken(ctx *middleware.Context, handler GetRegisterConfirmationTokenHandler) *GetRegisterConfirmationToken {
	return &GetRegisterConfirmationToken{Context: ctx, Handler: handler}
}

/*GetRegisterConfirmationToken swagger:route GET /register-confirmation/{token} register getRegisterConfirmationToken

GetRegisterConfirmationToken get register confirmation token API

*/
type GetRegisterConfirmationToken struct {
	Context *middleware.Context
	Handler GetRegisterConfirmationTokenHandler
}

func (o *GetRegisterConfirmationToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRegisterConfirmationTokenParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
