// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// GetRegisterConfirmationTokenOKCode is the HTTP code returned for type GetRegisterConfirmationTokenOK
const GetRegisterConfirmationTokenOKCode int = 200

/*GetRegisterConfirmationTokenOK OK

swagger:response getRegisterConfirmationTokenOK
*/
type GetRegisterConfirmationTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetRegisterConfirmationTokenOK creates GetRegisterConfirmationTokenOK with default headers values
func NewGetRegisterConfirmationTokenOK() *GetRegisterConfirmationTokenOK {

	return &GetRegisterConfirmationTokenOK{}
}

// WithPayload adds the payload to the get register confirmation token o k response
func (o *GetRegisterConfirmationTokenOK) WithPayload(payload *models.GeneralResponse) *GetRegisterConfirmationTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get register confirmation token o k response
func (o *GetRegisterConfirmationTokenOK) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegisterConfirmationTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRegisterConfirmationTokenBadRequestCode is the HTTP code returned for type GetRegisterConfirmationTokenBadRequest
const GetRegisterConfirmationTokenBadRequestCode int = 400

/*GetRegisterConfirmationTokenBadRequest BAD REQUEST

swagger:response getRegisterConfirmationTokenBadRequest
*/
type GetRegisterConfirmationTokenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetRegisterConfirmationTokenBadRequest creates GetRegisterConfirmationTokenBadRequest with default headers values
func NewGetRegisterConfirmationTokenBadRequest() *GetRegisterConfirmationTokenBadRequest {

	return &GetRegisterConfirmationTokenBadRequest{}
}

// WithPayload adds the payload to the get register confirmation token bad request response
func (o *GetRegisterConfirmationTokenBadRequest) WithPayload(payload *models.GeneralResponse) *GetRegisterConfirmationTokenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get register confirmation token bad request response
func (o *GetRegisterConfirmationTokenBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegisterConfirmationTokenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRegisterConfirmationTokenUnauthorizedCode is the HTTP code returned for type GetRegisterConfirmationTokenUnauthorized
const GetRegisterConfirmationTokenUnauthorizedCode int = 401

/*GetRegisterConfirmationTokenUnauthorized UNAUTHORIZED

swagger:response getRegisterConfirmationTokenUnauthorized
*/
type GetRegisterConfirmationTokenUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetRegisterConfirmationTokenUnauthorized creates GetRegisterConfirmationTokenUnauthorized with default headers values
func NewGetRegisterConfirmationTokenUnauthorized() *GetRegisterConfirmationTokenUnauthorized {

	return &GetRegisterConfirmationTokenUnauthorized{}
}

// WithPayload adds the payload to the get register confirmation token unauthorized response
func (o *GetRegisterConfirmationTokenUnauthorized) WithPayload(payload *models.GeneralResponse) *GetRegisterConfirmationTokenUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get register confirmation token unauthorized response
func (o *GetRegisterConfirmationTokenUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegisterConfirmationTokenUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRegisterConfirmationTokenForbiddenCode is the HTTP code returned for type GetRegisterConfirmationTokenForbidden
const GetRegisterConfirmationTokenForbiddenCode int = 403

/*GetRegisterConfirmationTokenForbidden FORBIDDEN

swagger:response getRegisterConfirmationTokenForbidden
*/
type GetRegisterConfirmationTokenForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetRegisterConfirmationTokenForbidden creates GetRegisterConfirmationTokenForbidden with default headers values
func NewGetRegisterConfirmationTokenForbidden() *GetRegisterConfirmationTokenForbidden {

	return &GetRegisterConfirmationTokenForbidden{}
}

// WithPayload adds the payload to the get register confirmation token forbidden response
func (o *GetRegisterConfirmationTokenForbidden) WithPayload(payload *models.GeneralResponse) *GetRegisterConfirmationTokenForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get register confirmation token forbidden response
func (o *GetRegisterConfirmationTokenForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegisterConfirmationTokenForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRegisterConfirmationTokenNotFoundCode is the HTTP code returned for type GetRegisterConfirmationTokenNotFound
const GetRegisterConfirmationTokenNotFoundCode int = 404

/*GetRegisterConfirmationTokenNotFound NOT FOUND

swagger:response getRegisterConfirmationTokenNotFound
*/
type GetRegisterConfirmationTokenNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetRegisterConfirmationTokenNotFound creates GetRegisterConfirmationTokenNotFound with default headers values
func NewGetRegisterConfirmationTokenNotFound() *GetRegisterConfirmationTokenNotFound {

	return &GetRegisterConfirmationTokenNotFound{}
}

// WithPayload adds the payload to the get register confirmation token not found response
func (o *GetRegisterConfirmationTokenNotFound) WithPayload(payload *models.GeneralResponse) *GetRegisterConfirmationTokenNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get register confirmation token not found response
func (o *GetRegisterConfirmationTokenNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegisterConfirmationTokenNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRegisterConfirmationTokenInternalServerErrorCode is the HTTP code returned for type GetRegisterConfirmationTokenInternalServerError
const GetRegisterConfirmationTokenInternalServerErrorCode int = 500

/*GetRegisterConfirmationTokenInternalServerError INTERNAL SERVER ERROR

swagger:response getRegisterConfirmationTokenInternalServerError
*/
type GetRegisterConfirmationTokenInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetRegisterConfirmationTokenInternalServerError creates GetRegisterConfirmationTokenInternalServerError with default headers values
func NewGetRegisterConfirmationTokenInternalServerError() *GetRegisterConfirmationTokenInternalServerError {

	return &GetRegisterConfirmationTokenInternalServerError{}
}

// WithPayload adds the payload to the get register confirmation token internal server error response
func (o *GetRegisterConfirmationTokenInternalServerError) WithPayload(payload *models.GeneralResponse) *GetRegisterConfirmationTokenInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get register confirmation token internal server error response
func (o *GetRegisterConfirmationTokenInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegisterConfirmationTokenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
