// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Prashanth-GS/test-swagger/models"
)

// GetCallbackGoogleOKCode is the HTTP code returned for type GetCallbackGoogleOK
const GetCallbackGoogleOKCode int = 200

/*GetCallbackGoogleOK OK

swagger:response getCallbackGoogleOK
*/
type GetCallbackGoogleOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleOK creates GetCallbackGoogleOK with default headers values
func NewGetCallbackGoogleOK() *GetCallbackGoogleOK {

	return &GetCallbackGoogleOK{}
}

// WithPayload adds the payload to the get callback google o k response
func (o *GetCallbackGoogleOK) WithPayload(payload *models.LoginResponse) *GetCallbackGoogleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google o k response
func (o *GetCallbackGoogleOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleBadRequestCode is the HTTP code returned for type GetCallbackGoogleBadRequest
const GetCallbackGoogleBadRequestCode int = 400

/*GetCallbackGoogleBadRequest BAD REQUEST

swagger:response getCallbackGoogleBadRequest
*/
type GetCallbackGoogleBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleBadRequest creates GetCallbackGoogleBadRequest with default headers values
func NewGetCallbackGoogleBadRequest() *GetCallbackGoogleBadRequest {

	return &GetCallbackGoogleBadRequest{}
}

// WithPayload adds the payload to the get callback google bad request response
func (o *GetCallbackGoogleBadRequest) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google bad request response
func (o *GetCallbackGoogleBadRequest) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleUnauthorizedCode is the HTTP code returned for type GetCallbackGoogleUnauthorized
const GetCallbackGoogleUnauthorizedCode int = 401

/*GetCallbackGoogleUnauthorized UNAUTHORIZED

swagger:response getCallbackGoogleUnauthorized
*/
type GetCallbackGoogleUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleUnauthorized creates GetCallbackGoogleUnauthorized with default headers values
func NewGetCallbackGoogleUnauthorized() *GetCallbackGoogleUnauthorized {

	return &GetCallbackGoogleUnauthorized{}
}

// WithPayload adds the payload to the get callback google unauthorized response
func (o *GetCallbackGoogleUnauthorized) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google unauthorized response
func (o *GetCallbackGoogleUnauthorized) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleForbiddenCode is the HTTP code returned for type GetCallbackGoogleForbidden
const GetCallbackGoogleForbiddenCode int = 403

/*GetCallbackGoogleForbidden FORBIDDEN

swagger:response getCallbackGoogleForbidden
*/
type GetCallbackGoogleForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleForbidden creates GetCallbackGoogleForbidden with default headers values
func NewGetCallbackGoogleForbidden() *GetCallbackGoogleForbidden {

	return &GetCallbackGoogleForbidden{}
}

// WithPayload adds the payload to the get callback google forbidden response
func (o *GetCallbackGoogleForbidden) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google forbidden response
func (o *GetCallbackGoogleForbidden) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleNotFoundCode is the HTTP code returned for type GetCallbackGoogleNotFound
const GetCallbackGoogleNotFoundCode int = 404

/*GetCallbackGoogleNotFound NOT FOUND

swagger:response getCallbackGoogleNotFound
*/
type GetCallbackGoogleNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleNotFound creates GetCallbackGoogleNotFound with default headers values
func NewGetCallbackGoogleNotFound() *GetCallbackGoogleNotFound {

	return &GetCallbackGoogleNotFound{}
}

// WithPayload adds the payload to the get callback google not found response
func (o *GetCallbackGoogleNotFound) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google not found response
func (o *GetCallbackGoogleNotFound) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCallbackGoogleInternalServerErrorCode is the HTTP code returned for type GetCallbackGoogleInternalServerError
const GetCallbackGoogleInternalServerErrorCode int = 500

/*GetCallbackGoogleInternalServerError INTERNAL SERVER ERROR

swagger:response getCallbackGoogleInternalServerError
*/
type GetCallbackGoogleInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralResponse `json:"body,omitempty"`
}

// NewGetCallbackGoogleInternalServerError creates GetCallbackGoogleInternalServerError with default headers values
func NewGetCallbackGoogleInternalServerError() *GetCallbackGoogleInternalServerError {

	return &GetCallbackGoogleInternalServerError{}
}

// WithPayload adds the payload to the get callback google internal server error response
func (o *GetCallbackGoogleInternalServerError) WithPayload(payload *models.GeneralResponse) *GetCallbackGoogleInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get callback google internal server error response
func (o *GetCallbackGoogleInternalServerError) SetPayload(payload *models.GeneralResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallbackGoogleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
