// Code generated by go-swagger; DO NOT EDIT.

package register

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostRegisterDetailsHandlerFunc turns a function with the right signature into a post register details handler
type PostRegisterDetailsHandlerFunc func(PostRegisterDetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRegisterDetailsHandlerFunc) Handle(params PostRegisterDetailsParams) middleware.Responder {
	return fn(params)
}

// PostRegisterDetailsHandler interface for that can handle valid post register details params
type PostRegisterDetailsHandler interface {
	Handle(PostRegisterDetailsParams) middleware.Responder
}

// NewPostRegisterDetails creates a new http.Handler for the post register details operation
func NewPostRegisterDetails(ctx *middleware.Context, handler PostRegisterDetailsHandler) *PostRegisterDetails {
	return &PostRegisterDetails{Context: ctx, Handler: handler}
}

/*PostRegisterDetails swagger:route POST /register-details register postRegisterDetails

PostRegisterDetails post register details API

*/
type PostRegisterDetails struct {
	Context *middleware.Context
	Handler PostRegisterDetailsHandler
}

func (o *PostRegisterDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostRegisterDetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
